kind: pipeline
name: default

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment: 
      SONARTOKEN:
        from_secret: sonarToken
    commands:
      - cd ConsoleApp1/
      - dotnet sonarscanner begin
        /k:"easv-devops_PV-Calculator_AY3fwmh5EVvRW2O60EHr"
        /d:sonar.host.url="http://sonar.setgo.dk:9000"
        /d:sonar.token="#SONARTOKEN"
        /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARTOKEN"